version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: swapi
    container_name: swapi
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=$DATABASE_URL
      - BASE_URL=$BASE_URL
    ports:
      - "6000:6000"
    volumes:
      - .:/usr/src/app